title: "[Feature]: <Short description>"
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."
      placeholder: I need to see which emails failed, but there is no dashboard...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Add a /stats endpoint or a visual dashboard to see bounce rates.
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Business Impact
      description: How much does this help you?
      options:
        - "High: This is a dealbreaker for me"
        - "Medium: It would save me time"
        - "Low: Just a nice visual tweak"
    validations:
      required: true