name: 🔌 Adapter Bug Report
description: Create a report to help us improve a specific adapter (e.g., SES, SendGrid).
title: "[Adapter Bug]: "
labels: ["bug", "scope: adapter"]
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ SECURITY WARNING: PUBLIC REPOSITORY ⚠️

        **This issue will be visible to the entire world.** Please ensure you **DO NOT** include real credentials.

  - type: input
    id: adapter
    attributes:
      label: Failing Adapter Package
      description: Please enter the exact package name.
      placeholder: "@thormail/adapter-ses"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NPM Package Version
      placeholder: e.g. 1.0.2
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Code
      description: Provide a minimal code snippet. Replace real API Keys with placeholders.
      render: javascript
      placeholder: |
        // ✅ GOOD: Uses placeholder
        const adapter = new SESAdapter({ apiKey: 'YOUR_API_KEY' });
        await adapter.send({ ... });
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Stack Trace / Logs
      render: shell

  - type: checkboxes
    id: security_check
    attributes:
      label: Security Confirmation
      options:
        - label: I confirm that I have scrubbed all API Keys and sensitive credentials from the code snippets above.
          required: true
