name: 🐛 Core Bug Report
description: Report an issue with the main ThorMail orchestrator.
title: "[Core Bug]: "
labels: ["bug", "scope: core"]
body:
  - type: markdown
    attributes:
      value: |
        **Security Warning:** Do not post API Keys or passwords.

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: What happened?
    validations:
      required: true